CREATE TABLE IF NOT EXISTS `robot` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `map_id` int(11),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `measurement` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `one` int(11) NOT NULL,
  `two` int(11) NOT NULL,
  `q0` FLOAT NOT NULL,
  `q1` FLOAT NOT NULL,
  `q2` FLOAT NOT NULL,
  `q3` FLOAT NOT NULL,
  `t0` FLOAT NOT NULL,
  `t1` FLOAT NOT NULL,
  `t2` FLOAT NOT NULL,
  `type` CHAR(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `keyframe` (
  `id` BIGINT NOT NULL,
  `map_id` int(11) NOT NULL,
  `q0` FLOAT NOT NULL,
  `q1` FLOAT NOT NULL,
  `q2` FLOAT NOT NULL,
  `q3` FLOAT NOT NULL,
  `t0` FLOAT NOT NULL,
  `t1` FLOAT NOT NULL,
  `t2` FLOAT NOT NULL,
  `int0` FLOAT NOT NULL,
  `int1` FLOAT NOT NULL,
  `int2` FLOAT NOT NULL,
  `rgb` MEDIUMBLOB NOT NULL,
  `depth` MEDIUMBLOB NOT NULL,
  `keypoints` MEDIUMBLOB NOT NULL,
  `descriptors` MEDIUMBLOB NOT NULL,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

